# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-88c29497-e40a-47f9-9d38-64d7808d67f8";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-88c29497-e40a-47f9-9d38-64d7808d67f8".device =
    "/dev/disk/by-uuid/88c29497-e40a-47f9-9d38-64d7808d67f8";

  fileSystems."/media/jibi/kb" = {
    device = "systemd-1";
    fsType = "autofs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/31D8-944F";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
